version: '0'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=luxonis
  scraper:
    build: .
    command: ["./postgres-wait.sh", "db", "python", "sreality_spider.py"]
    environment:
      - POSTGRES_PASSWORD=luxonis
    volumes:
      - .:/code
    depends_on:
      - db
  web:
    build: .
    environment:
      - POSTGRES_PASSWORD=luxonis
    command: python main.py
    volumes:
      - .:/code
    ports:
      - 8080:8080
    depends_on:
      - db